#!/bin/bash
# Auto Pull, Build, Deploy and Watch Script
# This script pulls changes from remote ClaudeCode, builds, deploys, and watches for errors

set -e

echo "🔄 Auto Pull, Build, Deploy and Watch"
echo "======================================"

# Ensure we're on ClaudeCode branch
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "ClaudeCode" ]; then
    echo "⚠️  Not on ClaudeCode branch. Switching..."
    git checkout ClaudeCode
fi

# Pull latest changes from remote
echo "📥 Pulling latest changes from origin/ClaudeCode..."
git pull origin ClaudeCode

# Install/update dependencies
echo "📦 Installing/updating dependencies..."
npm install

# Build the project
echo "🏗️ Running CDS build..."
BUILD_EXIT_CODE=0
npm run build || BUILD_EXIT_CODE=$?

if [ $BUILD_EXIT_CODE -ne 0 ]; then
    echo "❌ Build failed! Attempting auto-fix..."

    # Auto-fix common ES module issues
    echo "🔧 Fixing ES module syntax..."
    find srv -name "*.js" -type f -print0 | while IFS= read -r -d '' file; do
        if grep -q "require('@sap/cds')" "$file"; then
            sed -i "s/const cds = require('@sap\/cds')/import cds from '@sap\/cds'/g" "$file"
            sed -i "s/module.exports = class/export default class/g" "$file"
            sed -i "s/module.exports = /export default /g" "$file"
            echo "  Fixed: $file"
        fi
    done

    # Retry build
    echo "🔄 Retrying build after fixes..."
    if npm run build; then
        echo "✅ Build successful after auto-fix!"

        # Commit and push fixes
        git add -A
        if git diff --staged --quiet; then
            echo "No changes to commit"
        else
            git commit -m "Auto-fix: Build errors resolved

🤖 Generated by auto-pull-build-watch script"
            echo "📤 Pushing fixes to origin/ClaudeCode..."
            git push origin ClaudeCode

            # Merge to dev on remote using GitHub CLI
            echo "🔀 Merging ClaudeCode to dev on remote..."
            gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/:owner/:repo/merges \
                -f base='dev' \
                -f head='ClaudeCode' \
                -f commit_message='Auto-merge: ClaudeCode to dev after build fix' || echo "⚠️  Merge may require manual intervention"
        fi
    else
        echo "❌ Build still failing after auto-fix. Manual intervention required."
        exit 1
    fi
fi

# Deploy to database
echo "🚀 Running CDS deploy..."
if cds deploy; then
    echo "✅ Deploy successful!"
else
    echo "❌ Deploy failed!"
    exit 1
fi

# Watch for changes
echo "👀 Starting CDS watch..."
echo "   Press Ctrl+C to stop"
cds watch
