@echo off
REM Auto Pull, Build, Deploy and Watch Script for Windows
REM This script pulls changes from remote ClaudeCode, builds, deploys, and watches for errors

echo.
echo Auto Pull, Build, Deploy and Watch
echo ======================================
echo.

REM Ensure we're on ClaudeCode branch
for /f "tokens=*" %%i in ('git branch --show-current') do set CURRENT_BRANCH=%%i
if not "%CURRENT_BRANCH%"=="ClaudeCode" (
    echo Not on ClaudeCode branch. Switching...
    git checkout ClaudeCode
)

REM Pull latest changes from remote
echo Pulling latest changes from origin/ClaudeCode...
git pull origin ClaudeCode
if errorlevel 1 (
    echo Failed to pull changes
    exit /b 1
)

REM Install/update dependencies
echo Installing/updating dependencies...
call npm install
if errorlevel 1 (
    echo Failed to install dependencies
    exit /b 1
)

REM Build the project
echo Running CDS build...
call npm run build
if errorlevel 1 (
    echo Build failed! Attempting auto-fix...

    REM Auto-fix common ES module issues
    echo Fixing ES module syntax in service files...
    powershell -Command "Get-ChildItem -Path srv -Filter *.js -Recurse | ForEach-Object { (Get-Content $_.FullName) -replace \"const cds = require\('@sap/cds'\)\", \"import cds from '@sap/cds'\" -replace \"module.exports = class\", \"export default class\" | Set-Content $_.FullName }"

    REM Retry build
    echo Retrying build after fixes...
    call npm run build
    if errorlevel 1 (
        echo Build still failing after auto-fix. Manual intervention required.
        exit /b 1
    )

    echo Build successful after auto-fix!

    REM Commit and push fixes
    git add -A
    git diff --staged --quiet
    if errorlevel 1 (
        git commit -m "Auto-fix: Build errors resolved" -m "" -m "Generated by auto-pull-build-watch script"
        echo Pushing fixes to origin/ClaudeCode...
        git push origin ClaudeCode

        REM Merge to dev on remote using GitHub CLI
        echo Merging ClaudeCode to dev on remote...
        gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/:owner/:repo/merges -f base=dev -f head=ClaudeCode -f commit_message="Auto-merge: ClaudeCode to dev after build fix"
    )
)

echo Build successful!

REM Deploy to database
echo Running CDS deploy...
call cds deploy
if errorlevel 1 (
    echo Deploy failed!
    exit /b 1
)

echo Deploy successful!

REM Watch for changes
echo Starting CDS watch...
echo Press Ctrl+C to stop
call cds watch
